image: node:latest

stages:
  - build
  - deploy

# Prod
build_prod:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy_prod:
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y libssl-dev
    - apt-get install -y lftp
  environment:
    name: prod
  script:
    - lftp sftp://$USERNAME:$PASSWORD@$HOST:$PORT -e "$LFTP_CMD"
  only:
    - master
  dependencies:
    - build_prod
